Models/CRUD_MVCModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace CRUD_MVC.Models
{
    public class Employees
    {
#nullable enable
        [Key]
        public int EmployeeID { get; set; }

        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string? Title { get; set; }

        public string? TitleOfCourtesy { get; set; }
        public DateTime? BirthDate { get; set; }
        public DateTime? HireDate { get; set; }
        public string? Address { get; set; }
        public string? City { get; set; }
        public string? Region { get; set; }
        public string? PostalCode { get; set; }
        public string? Country { get; set; }
        public string? HomePhone { get; set; }

        public string? Extension { get; set; }
        public int? ReportsTo { get; set; }
    }
}

Models/ErrorViewModel.cs
namespace CRUD_MVC.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Controllers/CRUD_MVCController.cs
using System;
using System.Diagnostics;
using CRUD_MVC.Data;
using CRUD_MVC.Models;
using Microsoft.AspNetCore.Mvc;

namespace CRUD_MVC.Controllers;

public class CRUD_MVCController : Controller
{
    private readonly NorthwindDbContext _db;

    private readonly ILogger<CRUD_MVCController> _logger;

    public CRUD_MVCController(ILogger<CRUD_MVCController> logger, NorthwindDbContext db)
    {
        _logger = logger;
        _db = db;
    }

    public IActionResult Index()
    {
        var employeeList = _db.Employees.ToList();
        return View(employeeList);
    }

    [HttpGet]
    public IActionResult AddEmployee()
    {
        return View();
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult AddEmployee(Employees obj)
    {
        if (ModelState.IsValid)
        {
            _db.Employees.Add(obj);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }
        return Json(obj);
    }

    [HttpGet]
    public IActionResult EditEmployee(int? EmployeeID)
    {
        if (EmployeeID == null || EmployeeID == 0)
        {
            return NotFound();
        }
        var obj = _db.Employees.Find(EmployeeID);
        return View(obj);
    }

    [HttpPost]
    public IActionResult EditEmployee(Employees model)
    {
        if (ModelState.IsValid)
        {
            var existingEmployee = _db.Employees.Find(model.EmployeeID);

            if (existingEmployee != null)
            {
                existingEmployee.LastName = model.LastName;
                existingEmployee.FirstName = model.FirstName;
                existingEmployee.Title = model.Title;
                existingEmployee.TitleOfCourtesy = model.TitleOfCourtesy;
                existingEmployee.BirthDate = model.BirthDate;
                existingEmployee.HireDate = model.HireDate;
                existingEmployee.Address = model.Address;
                existingEmployee.City = model.City;
                existingEmployee.Region = model.Region;
                existingEmployee.PostalCode = model.PostalCode;
                existingEmployee.Country = model.Country;
                existingEmployee.HomePhone = model.HomePhone;
                existingEmployee.Extension = model.Extension;
                existingEmployee.ReportsTo = model.ReportsTo;

                _db.SaveChanges();
            }
        }

        return RedirectToAction("Index");
    }

    [HttpGet]
    public IActionResult DeleteEmployee(int id)
    {
        try
        {
            var obj = _db.Employees.Find(id);

            if (obj == null)
            {
                return Json(new { success = false, error = "Record not found." });
            }

            _db.Employees.Remove(obj);
            _db.SaveChanges();

            return RedirectToAction("index");
        }
        catch (Exception ex)
        {
            return Json(new { success = false, error = ex.Message });
        }
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(
            new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier }
        );
    }
}

Views/CRUD_Mvc/AddEmployee.cshtml
@model Employees

<form method="post">
  <div class="border p-3 mt-4">
    <div class="row pb-2">
      <h2 class="Text primary">Add Employee</h2>
      <hr />
    </div>

    <div asp-validation-summary="All"></div>

    <div class="row">
      <div class="col-md-6">
        <div class="mb-3">
            <label asp-for="LastName"></label>
            <input required asp-for="LastName" class="form-control"/>
            <span asp-validation-for="LastName" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="FirstName"></label>
            <input asp-for="FirstName" class="form-control"/>
            <span asp-validation-for="FirstName" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="Title"></label>
            <input asp-for="Title" class="form-control"/>
            <span asp-validation-for="Title" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="TitleOfCourtesy"></label>
            <input asp-for="TitleOfCourtesy" class="form-control"/>
            <span asp-validation-for="TitleOfCourtesy" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="BirthDate"></label>
            <input asp-for="BirthDate" class="form-control"/>
            <span asp-validation-for="BirthDate" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="HireDate"></label>
            <input asp-for="HireDate" class="form-control"/>
            <span asp-validation-for="HireDate" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="Address"></label>
            <input asp-for="Address" class="form-control"/>
            <span asp-validation-for="Address" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="City"></label>
            <input asp-for="City" class="form-control"/>
            <span asp-validation-for="City" class="text-danger"></span>
        </div>
      </div>

      <div class="col-md-6">
        <div class="mb-3">
            <label asp-for="Region"></label>
            <input asp-for="Region" class="form-control"/>
            <span asp-validation-for="Region" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="PostalCode"></label>
            <input asp-for="PostalCode" class="form-control"/>
            <span asp-validation-for="PostalCode" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="Country"></label>
            <input asp-for="Country" class="form-control"/>
            <span asp-validation-for="Country" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="HomePhone"></label>
            <input asp-for="HomePhone" class="form-control"/>
            <span asp-validation-for="HomePhone" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="Extension"></label>
            <input asp-for="Extension" class="form-control"/>
            <span asp-validation-for="Extension" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="ReportsTo"></label>
            <input asp-for="ReportsTo" class="form-control"/>
            <span asp-validation-for="ReportsTo" class="text-danger"></span>
        </div>

        <button type="submit" class="btn btn-outline-success" asp-action="AddEmployee">Add</button>
        <a asp-controller="CRUD_MVC" asp-action="Index" class="btn btn-outline-dark">Back</a>
      </div>
    </div>
  </div>
</form>

@section Scripts
{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

Views/CRUD_Mvc/EditEmployee.cshtml
@model Employees

<form method="post" asp-action="Edit">
  <div class="border p-3 mt-4">
    <div class="row pb-2">
      <h2 class="Text primary">Edit Employee</h2>
      <hr />
    </div>

    <div asp-validation-summary="All"></div>

    <div class="row">
      <input type="hidden" asp-for="EmployeeID" />

      <div class="col-md-6">
        <div class="mb-3">
            <label asp-for="LastName"></label>
            <input required asp-for="LastName" class="form-control"/>
            <span asp-validation-for="LastName" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="FirstName"></label>
            <input asp-for="FirstName" class="form-control"/>
            <span asp-validation-for="FirstName" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="Title"></label>
            <input asp-for="Title" class="form-control"/>
            <span asp-validation-for="Title" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="TitleOfCourtesy"></label>
            <input asp-for="TitleOfCourtesy" class="form-control"/>
            <span asp-validation-for="TitleOfCourtesy" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="BirthDate"></label>
            <input asp-for="BirthDate" class="form-control"/>
            <span asp-validation-for="BirthDate" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="HireDate"></label>
            <input asp-for="HireDate" class="form-control"/>
            <span asp-validation-for="HireDate" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="Address"></label>
            <input asp-for="Address" class="form-control"/>
            <span asp-validation-for="Address" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="City"></label>
            <input asp-for="City" class="form-control"/>
            <span asp-validation-for="City" class="text-danger"></span>
        </div>
      </div>

      <div class="col-md-6"> 
        <div class="mb-3">
            <label asp-for="Region"></label>
            <input asp-for="Region" class="form-control"/>
            <span asp-validation-for="Region" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="PostalCode"></label>
            <input asp-for="PostalCode" class="form-control"/>
            <span asp-validation-for="PostalCode" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="Country"></label>
            <input asp-for="Country" class="form-control"/>
            <span asp-validation-for="Country" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="HomePhone"></label>
            <input asp-for="HomePhone" class="form-control"/>
            <span asp-validation-for="HomePhone" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="Extension"></label>
            <input asp-for="Extension" class="form-control"/>
            <span asp-validation-for="Extension" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="ReportsTo"></label>
            <input asp-for="ReportsTo" class="form-control"/>
            <span asp-validation-for="ReportsTo" class="text-danger"></span>
        </div>

        <button type="submit" class="btn btn-outline-primary" asp-action="EditEmployee">Save</button>
        <a asp-controller="CRUD_MVC" asp-action="Index" class="btn btn-outline-dark">Back</a>
      </div>
    </div>
  </div>
</form>

@section Scripts
{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

Views/CRUD_Mvc/Index.cshtml
@model List<CRUD_MVC.Models.Employees>
@{
    ViewData["Title"] = "Employees";
    
}

<h1 class="title">Employees</h1>

<div>
    <a class="btn btn-outline-success add-Button" href="@Url.Action("AddEmployee", "CRUD_MVC")">Add Employee</a>
</div>

<table  class="table table-bordered table-striped">
<thead>
    <tr>
        <th>
            EmployeeID
        </th>
        <th>
            LastName
        </th>
        <th>
            FirstName
        </th>
        <th>
            Title
        </th>
        <th>
            TitleOfCourtesy
        </th>
        <th>
            BirthDate
        </th>
        <th>
            HireDate
        </th>
        <th>
            Address
        </th>
        <th>
            City
        </th>
        <th>
            Region
        </th>
        <th>
            PostalCode
        </th>
        <th>
            Country
        </th>
        <th>
            HomePhone
        </th>
        <th>
            Extension
        </th>
        <th>
            Reports
        </th>
        <th>
            Delete
        </th>
    </tr>
</thead>
<tbody>
    @foreach(var obj in Model)
    {
        <tr>
            <td>
            @obj.EmployeeID
            <a asp-controller="CRUD_MVC" asp-action="EditEmployee" asp-route-Employeeid="@obj.EmployeeID">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pen" viewBox="0 0 16 16">
                    <path d="m13.498.795.149-.149a1.207 1.207 0 1 1 1.707 1.708l-.149.148a1.5 1.5 0 0 1-.059 2.059L4.854 14.854a.5.5 0 0 1-.233.131l-4 1a.5.5 0 0 1-.606-.606l1-4a.5.5 0 0 1 .131-.232l9.642-9.642a.5.5 0 0 0-.642.056L6.854 4.854a.5.5 0 1 1-.708-.708L9.44.854A1.5 1.5 0 0 1 11.5.796a1.5 1.5 0 0 1 1.998-.001m-.644.766a.5.5 0 0 0-.707 0L1.95 11.756l-.764 3.057 3.057-.764L14.44 3.854a.5.5 0 0 0 0-.708z"/>
                    </svg>
                </a>
            </td>
            <td>
                @obj.LastName
            </td>
            <td>
                @obj.FirstName
            </td>
            <td>
                @obj.Title
            </td>
            <td>
                @obj.TitleOfCourtesy
            </td>
            <td>
                @obj.BirthDate?.ToString("dd.MM.yyyy")
            </td>
            <td>
                @obj.HireDate?.ToString("dd.MM.yyyy")
            </td>
            <td>
                @obj.Address
            </td>
            <td>
                @obj.City
            </td>
            <td>
                @obj.Region
            </td>
            <td>
                @obj.PostalCode
            </td>
            <td>
                @obj.Country
            </td>
            <td>
                @obj.HomePhone
            </td>
            <td>
                @obj.Extension
            </td>
            <td>
                @obj.ReportsTo
            </td>
            
            <td>
                <a id="deleteEmployeeButton" href="#" style="color: red;" onclick="confirmDelete(@obj.EmployeeID)"> 
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash3" viewBox="0 0 16 16">
                    <path d="M6.5 1h3a.5.5 0 0 1 .5.5v1H6v-1a.5.5 0 0 1 .5-.5M11 2.5v-1A1.5 1.5 0 0 0 9.5 0h-3A1.5 1.5 0 0 0 5 1.5v1H1.5a.5.5 0 0 0 0 1h.538l.853 10.66A2 2 0 0 0 4.885 16h6.23a2 2 0 0 0 1.994-1.84l.853-10.66h.538a.5.5 0 0 0 0-1zm1.958 1-.846 10.58a1 1 0 0 1-.997.92h-6.23a1 1 0 0 1-.997-.92L3.042 3.5zm-7.487 1a.5.5 0 0 1 .528.47l.5 8.5a.5.5 0 0 1-.998.06L5 5.03a.5.5 0 0 1 .47-.53Zm5.058 0a.5.5 0 0 1 .47.53l-.5 8.5a.5.5 0 1 1-.998-.06l.5-8.5a.5.5 0 0 1 .528-.47M8 4.5a.5.5 0 0 1 .5.5v8.5a.5.5 0 0 1-1 0V5a.5.5 0 0 1 .5-.5"/>
                    </svg>
                </a>
            </td>
        </tr>
    }
</tbody>
</table>


@section Styles{
    
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">
    <link type="text/css" href="/css/Employees.css" rel="stylesheet" />
}
@section Scripts{

  @{
    await Html.RenderPartialAsync("_ValidationScriptsPartial");
  }
  <script src="/js/Employee.js?v=1.1"></script>

  

}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CRUD_MVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CRUD_MVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="CRUD_MVC" asp-action="Index">CRUD_MVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="CRUD_MVC" asp-action="Index">Employee</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
    @await RenderSectionAsync("Styles", required: false)
</body>
</html>